### ISSUE TITLE
Notice: Undefined index: bundle in FeedsProcessor->bundle() 

### ISSUE THREAD

**Issue by dbourrion** [GetDKAN/dkan#1759]
Hi
On a fresh install of dkan, got a lot of 

>  Notice: Undefined index: bundle in FeedsProcessor->bundle() (line 64 of /var/www/html/dkan/profiles/dkan/modules/contrib/feeds/plugins/FeedsProcessor.inc).

**Comment by mohnjatthews** [comment]
I too received this error. It showed up when updating DKAN from the previous version.

**Comment by dirdigeng** [comment]
I also get this. Seems to be seeking some configuration data that is not (yet?) defined. Occurred after installation of DROPS-7 and after then accepting DKAN updates.

**Comment by janette** [comment]
@dirdigeng have you upgraded the feeds module? It is important to stick with the version that ships with the distribution.

**Comment by dafeder** [comment]
@dbourrion @dirdigeng we haven't been able to reproduce recently. Closing this issue as at least one of these seems to be due to upgrading a contrib module ahead of DKAN. Feeds in particular needs to be on the version specified in the DKAN makefile. Please re-open or reach out if you're still having issues.

**Comment by oriole9g** [comment]
I can confirm that this error appears when you update Feeds module as @dafeder and @janette have said.
