### ISSUE TITLE
I'm trying to create a CSV with geojson coordinates to work with leaflet in DKAN

### ISSUE THREAD

**Issue by Forester1** [GetDKAN/dkan#1800]
So, I'm trying to create a CSV with geojson coordinates to work with leaflet in DKAN so that boundaries can be easily displayed on the map. I have had some success and as an example I have hacked together a generalised polygon sub set of the boundary files http://opendata.cambridgeshireinsight.org.uk/dataset/broad-rental-market-areas-brma/resource/1fd886a2-75c1-4095-a470-a1edd84d9d85. The process for this was convoluted and as I follow up to this there will be hundreds of similar datasets that will require their boundaries to be prepared. Is there an easy way to transform geojson coordinates into csv so that they are compliant with leaflet in DKAN? 

In addition, when I attempt something similar for the full dataset it tells me that the "File was too large or unavailable for preview." The file is 1.3 Mb. This has been reduced from ~23mb in the boundary generalisation process. Any suggestions?

I hope this is the right forum to post this. I have looked around and can't quite find a solution to this. All help is really appreciated

**Comment by kimwdavidson** [comment]
Hi @forester1, sorry it's taken so long to get back to you, but definitely want to look into this bug and are adding it to the backlog. Thanks!

**Comment by tonyfujs** [comment]
Hi @Forester1 and @kimwdavidson,
I am also struggling with formatting and displaying geojson data in DKAN. Trying to answer some of your questions @Forester1:
* "The process for this was convoluted and as I follow up to this there will be hundreds of similar datasets that will require their boundaries to be prepared. Is there an easy way to transform geojson coordinates into csv so that they are compliant with leaflet in DKAN?"
Fully agree. In addition, it is not widely used... I talked to a few GIS specialists, and none of them had to deal with this type of format before.
Leaflet has no problem dealing with geosjon, my understanding is that the .csv formatting is a limitation of DKAN.
*  "In addition, when I attempt something similar for the full dataset it tells me that the "File was too large or unavailable for preview." The file is 1.3 Mb. This has been reduced from ~23mb in the boundary generalisation process. Any suggestions?"
Yes: Import your dataset to the DKAN datastore first. By default, files that are less than a certain amount  (I believe 3 or 5Mb) are displayed automatically. If your file is more than that, then it needs to be imported onto the datastore first in order to be displayed correctly.

Hope that helps.

@kimwdavidson Any plan to support other formats than .csv in DKAN?

**Comment by janette** [comment]
**Convert GeoJSON to CSV**
https://mygeodata.cloud/converter/geojson-to-csv
http://www.convertcsv.com/geojson-to-csv.htm

**Documentation**
http://visualization-entity.readthedocs.io/

**Comment by dafeder** [comment]
@tonyfujs we do support regular GeoJSON as well (and yes, we let leaflet handle it). If the format is not correctly auto-detected on upload, you can chose it manually with the format field. Here's an example of a GeoJSON resource:

http://dan.dkandemo.nuamsdev.com/dataset/resource/dc70f331-b7b5-45f1-8e5a-7d0583cabe4b

(this will probably only be online for a few days)

**Comment by dafeder** [comment]
Here is an example with points rather than polygons: 

http://dan.dkandemo.nuamsdev.com/dataset/resource/cb25bfeb-99cd-4da9-82c9-6d6382bcd09c

I agree that the CSV with geojson geometry column is not a format we see often these days - this is just something that's part of OKFN's recline map view tool that we use for the CSV visualizations. 

Here is the full list of data preview types supported:

https://docs.getdkan.com/en/latest/components/visualizations/datapreviews.html#additional-preview-types

**Comment by tonyfujs** [comment]
Thanks @dafeder and @janette very helpful!
