### ISSUE TITLE
Unknown data property field_modified_source_date

### ISSUE THREAD

**Issue by kevindavis338** [GetDKAN/dkan#1905]
EntityMetadataWrapperException: Unknown data property field_modified_source_date. in EntityStructureWrapper->getPropertyInfo() (line 355 of /var/www/html/sites/profiles/dkan/modules/contrib/entity/includes/entity.wrapper.inc).

**Comment by dafeder** [comment]
This issue appears in certain DKAN sites after upgrading to 1.13.3. It's fixed by https://github.com/NuCivic/dkan/commit/5af2172e8f9d5a5c18ac14e14e74612d5835816b#diff-f05ce6029c361ff80ee0bc826ec69741

But running the following code against your instance (with `drush php-eval` or using devel module's php tool) should give you a quick fix:

```
   // Mark the field for deletion.
   field_delete_field('field_modified_source_date');
   // Run the batch process to actually delete the field.
   $batch_size = 1;
   field_purge_batch($batch_size);
```

**Comment by kevindavis338** [comment]
Ok, thank you
