### ISSUE TITLE
Behat Test Revivification

### ISSUE THREAD

**Issue by eknapier** [GetDKAN/dkan#2183]
Several weaknesses in the current DKAN Behat suite should be addressed to ensure the most streamlined workflow, and to avoid false flag failures. Some specific strategies we've identified that would help towards this end:

- Adding additional cleanup methods to address problem areas in testing suite (i.e., adding call to clear cache in a post scenario hook targeting a particular behat tag. )
- Remove unnecessary, superfluous lines from Behat tests that do not explicitly test the scenario description. (i.e., see several instances of "And I wait for "No imported items."")
- Consider replacing final "THEN" steps reliant upon visible text strings with lines mapping to API level methods, to add clarity to Gherkin statements and for less fragility. Unless the scenario description clearly states that a purpose of the test is to verify the presence of a specific text string, then an API method may be preferred for testing the final outcome. 
- Consider deprecating some UI tests in favor of API / "service level" tests where such an approach is logical. For example, perhaps it is useful to have 1 UI test to fill out a certain node form, but multiple tests tracing the same UI steps is ultimately redundant, even if each is testing different outcomes. In these instances some UI tests could be deprecated in favor of tests that may not need a browser at all to verify, but rather just a few calls to DKAN/Drupal.

One important goal of this work: Allowing for all tests to run (in any order) with all DKAN modules enabled, including the DKAN Workflow module. This module is disabled currently because of Behat test failures and it is an ultimate goal for us to re-enable the DKAN Workflow module so that all tests in the full suite can run in any order or combination without unexpected test failures.

**Comment by dafeder** [comment]
Definitely seems like all the Rest API tests should move from Behat to PHPUnit...

**Comment by janette** [comment]
**Datastore tests**
The datastore tests are confirming that a user can delete the datastore, the UI steps to confirm that the datastore no longer exists require the user to go to the Manage Datastore tab and see 'No imported items'. So clunky for sure, but not entirely superfluous :) 

**DKAN Workflow clarification**
This module is disabled because not everyone needs this level of content moderation. It is an option to be enabled for those who would like it. Our test problem is that we want to run the dkan tests on client sites, and if a client site has dkan_workflow enabled then the UI interface changes enough that the standard dkan tests will not work. To get around this we **disable** all dkan_workflow modules to run the tests. Then there is a workflow.feature that **enables** dkan_workflow (@enableWorkflow) to run moderation tests compatible with the UI then **disables** dkan_workflow when finished.
