### ISSUE TITLE
WMS preview not working

### ISSUE THREAD

**Issue by chrodos** [GetDKAN/dkan#2194]
Hello everyone,

I am trying to add this WMS API resource to a Dataset: http://ndgishub.nd.gov/arcgis/services/All_Communications/MapServer/WMSServer? . According to the documentation, this WMS should be shown in preview ( I used the URL presented i nthe documentation). Unfortunately, I just see a preview of the XML file with request not found. 

these are the installed versions of DKAN on the server:

Drupal:        7.56
DKAN: (dkan-7.x-1.13.7)

Thank you in advance.

**Comment by stefaniefgray** [comment]
Hi @chrodos,

I'm sorry to hear you've been dealing with this issue; I remember you'd mentioned this on Slack as well. There's a bug in DKAN 1.13.7 where WMS and other map previews have not been loading properly, but we hope to have this fixed as of this week with the new 1.14 release.

We'll keep you posted on when this bug is fixed! In the meantime, thank you for bringing it to our attention.

Stefanie Gray
Project DKAN / CivicActions

**Comment by dafeder** [comment]
DKAN v1 issue, closing due to EOL.
