### ISSUE TITLE
Update Docker Containers to Use PHP 7

### ISSUE THREAD

**Issue by kimwdavidson** [GetDKAN/dkan#2319]

**Comment by makopov** [comment]
Are you expecting PHP 7 support in DKAN? In my testing, I've seen DKAN run fine on PHP 7.1 but throw lots of warning in PHP 7.2. Is this expected and are there plans to support future PHP versions?

**Comment by acouch** [comment]
@makopov we are planning on supporting PHP 7 and moving to it for our CI and local development. We are pretty close on the container: https://github.com/GetDKAN/dkan/pull/2541 .

**Comment by acouch** [comment]
We have an upgrade for the CLI container #2541 but need one as well for the web container. 

We should create a new Dockerfile using ``ubuntu 16.04`` similar to https://github.com/GetDKAN/dkan-docker/blob/master/.docker/php7-cli/Dockerfile

We have a [PHP 7 general one](https://github.com/GetDKAN/dkan-docker/blob/master/.docker/php7/Dockerfile) which we should not use because it uses circle as an upstream and has a bunch of stuff we don't need.

**Comment by fmizzell** [comment]
I ran php7mar against dkan in #2318 and the only critical issues are in the json-schema library. We should pay attention to errors in DKAN's dependent functionality when we update the containers.

**Comment by fmizzell** [comment]
Also, the tests pass running in a simple PHP 7.1 container: https://circleci.com/gh/GetDKAN/dkan/9982?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

**Comment by dafeder** [comment]
We're moving to [dkan-tools](http://github.com/GetDKAN/dkan-tools) to manage our docker config. That uses our getdkan/dkan-docker images, and have made tickets GetDKAN/dkan-docker#4 and GetDKAN/dkan-docker#5 to address. Can close this ticket once those tickets are resolved.
