### ISSUE TITLE
Change to less common default Admin username

### ISSUE THREAD

**Issue by erogray** [GetDKAN/dkan#2363]
Per Acquia Insight (Security category):

---

**Details**
Your admin username (User ID 1) is not complex. Simple usernames (including admin, administrator, and root) can represent a security vulnerability to your website.

**Actions / resolutions**
Change the username of your admin (User ID 1) to a complex name. Attackers can circumvent this best practice if you allow access to user profiles by anonymous or authenticated users, but it can still block automated attacks.

To change the username of your admin, on your website, open the People page at `/admin/people`, and then click the **edit** link on the row of your User ID 1 account. Edit the **Username**, and then click **Save**.

**Comment by janette** [comment]
Definitely not a different admin name for each site, we need something consistent for tests and our sanity.

**Comment by erogray** [comment]
@openprivacy do you have thoughts about the user1 username using "admin"? is there a best practice for this?

**Comment by openprivacy** [comment]
@erogray Best practice is to use default name admin and set a generated password that is not kept and no one knows. Seriously.
This is because no one should log in as uid=1 as that would be a shared account and accountability is lost.
If ever needed, users with local access to the system docroot can login as uid=1 via drush.
Otherwise, privileged users (with "administrator" role) should log in with username=firstname.lastname and email=firstname.lastname@civicactions.com
More info at https://civicactions-handbook.readthedocs.io/en/latest/05-engineering/security-compliance/#as-developers

**Comment by acouch** [comment]
Closing this ticket as it has not been updated recently and is not on our near-term roadmap. Please re-open if you would like to discuss further or are actively working on it.

**Comment by erogray** [comment]
This was updated 22 hours ago, and seems worth reviewing.
