### ISSUE TITLE
New Hero Unit image doesn't appear on the homepage

### ISSUE THREAD

**Issue by budda** [GetDKAN/dkan#2425]
If i upload a replacement hero image through the theme settings it saves fine but will not appear on the homepage as part of the background to the Hero panel.

**Comment by stefaniefgray** [comment]
Hi Budda,

I'm sorry you've been experiencing this issue. Let's get this sorted out so you can design your site as you please!

First of all, which version of DKAN are you running? Also, are you logged in as an admin or Site Manager? And just to be sure, you're editing under "NuBoot Radix settings," right?

I'd recommend flushing the site's caches, and waiting a few minutes to see if the hero image appears. Otherwise, please provide more detail as to what's happening during the process of adding a hero image, and we'll get it figured out.

Best regards,
Stefanie Gray
DKAN Support

**Comment by budda** [comment]
Looks like it might be solved by #2265 actually! Didn't show up as i was searching open only - hadn't realised so many additional releases had happened already this year.

**Comment by kimwdavidson** [comment]
@budda: I'm going to close this up. Let me know if you have any other questions!
