### ISSUE TITLE
Test clean up (1.16)

### ISSUE THREAD

**Issue by kimwdavidson** [GetDKAN/dkan#2573]
parent of #2256 Audit existing automated tests
parent of #2244 Replace CircleCI scripting with custom docker image
parent of #2243 Resolve automated testing random failures
parent of #2301 Check unit tests
parent of #2272 panels.feature tests failing locally
parent of #2271 group.admin.feature tests failing locally
parent of #2270 dkan_harvest.feature tests failing locally (closed)
parent of #2269 datastore_fast_import.feature tests failing locally

**Comment by janette** [comment]
@kimwdavidson 
- I think it would be helpful to list the titles of the children with the links on all epics so it is easy to fine things
- Also add checkboxes so we can see which items are done when viewing this ticket
- I don't see a ticket for creating a client site smoke test suite. Rather than running the full gamut of dkan tests we would run a limited set of tests that were specific to workflow being enabled or disabled plus any custom tests that cover custom functionality. We should add 
```
  dkan_workflow:
    enable: false
```
to the config.yml to determine which option to run.

**Comment by janette** [comment]
## Sites that do not display user log in link
Tests that use `Given I am logged in as a user with the "[x]" role` steps will fail because:
`Unable to determine if logged in because 'log_out' link cannot be found for user 'c9s7EL99' with role '[x]' (Exception)`
