### ISSUE TITLE
Confirm that all allowed extensions are also recognized by Harvest

### ISSUE THREAD

**Issue by erogray** [GetDKAN/dkan#2577]
It seems like Harvest can get throw errors when harvesting resource filetypes that are allowed by the site. The site-allowed filetypes should also be harvestable.

**Comment by erogray** [comment]
See also https://github.com/NuCivic/cadepttech/issues/60 and https://github.com/GetDKAN/dkan/issues/2575

**Comment by erogray** [comment]
can be tested by adding filetype to overrides that isn't normally allowed, then harvesting with fake json file that includes the unusual filetype.

**Comment by dafeder** [comment]
@erogray can you list some specific examples of this happening (with URLs) with some steps to reproduce?

**Comment by kimwdavidson** [comment]
this may no longer be an issue. @janette to test

**Comment by janette** [comment]
@stefaniefgray 
1. On a demo flavor site, add a custom extension via the UI `admin/dkan/dataset_forms`
2. create a json file to harvest that includes a resource with the custom extension http://myjson.com/
3. create a harvest source using the json you created
4. harvest and confirm the resource with the custom extension  was created

**Comment by stefaniefgray** [comment]
QA pass!

I did things a bit differently:

1. Allowed mp3 files on http://stefanie.dkandemo.nuamsdev.com and http://andrew.dkandemo.nuamsdev.com. (Note: After adding a new file format, clear the cache so that DKAN will allow you to upload that format.)

2. Uploaded a dataset with an mp3 to http://stefanie.dkandemo.nuamsdev.com/dataset/meow-meow-meow

3. Created a new Harvest from http://andrew.dkandemo.nuamsdev.com with keyword = "meow" and proceeded to Harvest from the Stefanie demo site.

4. Success! The mp3 resource is now located at http://andrew.dkandemo.nuamsdev.com/dataset/meow-meow-meow/resource/a60d6662-e62f-4df3-91e0-ec1a5f6ee5f0.

Ticket can be closed.
