### ISSUE TITLE
DKAN supporting DCAT-AP.de

### ISSUE THREAD

**Issue by eGovCologne** [GetDKAN/dkan#2595]
As a german national data-catalogue harverster (govdata.de) , I want to access a municipal dcat-ap catalogue, so that I can pull data from cities that use dkan.

All german municipal data providers are obliged to provide a data catalog following a new european/national standard called [DCAT-AP.de](https://www.dcat-ap.de/def/dcatde/1.0.1/spec/specification.pdf). When comparing the example file (see this [gist](https://gist.github.com/eGovCologne/8bf1030acb33e38df22d26ee30815f43)) with the dkan dcat-catalogue there seem to be some differences. 
Could you please take a look at the specification and provide some guidance on how to adapt/expand/configure the DKAN api to provide a national endpoint following the standard? Thanks!

**Comment by akuckartz** [comment]
A few hints:
* RDF/XML is the RDF serialisation which is probably the most ugly and least liked by the Semantic Web community. There are others like Turtle or JSON-LD which generally should be prefered. RDF serialisations can be converted into other RDF serialisations. You can contact me offline.
* DCAN supports the European DCAT application profile DCAT-AP but I do not know how well. DCAT-AP has a few additional restrictions.

**Comment by dafeder** [comment]
Thanks @akuckartz! We've found it challenging to understand exactly how to comply with the DCAT-AP standard, as there are many different implementations, country-specific standards, conflicting examples and different validators. The DCAT-AP endpoint that ships with DKAN was passing a generic European Commission-supported validator when it was released. It looks like this validator now lives at http://dcat-ap.semic.eu/dcat-ap_validator.html but is broken :\

Most people were requesting XML/RDF so that's what we focused on providing. If you have a current version of DKAN you should have a /catalog.xml that conforms to DCAT-AP.

**Comment by akuckartz** [comment]
The source code of that validator is available here: https://github.com/SEMICeu/dcat-ap_validator but it does not seem to be maintained.
@dafeder These are newer:
https://github.com/SEMICeu/dcat-ap_shacl
https://github.com/tenforce/vodap-dcatap-validation

**Comment by erogray** [comment]
DKAN 2 release will be coming up before long, and will probably be where we'll want to address this sort of enhancement.

**Comment by akuckartz** [comment]
#868 unfortunately was closed without resolving it.

**Comment by susisiman** [comment]
We have reopened #868 and will work on the user story for it.

**Comment by dafeder** [comment]
I think we can close this in favor of #868, we just need a basic pattern for supporting additional DCAT profiles/variants.
