### ISSUE TITLE
Consolidate workflow documentation pages

### ISSUE THREAD

**Issue by erogray** [GetDKAN/dkan#2614]
We have two Workflow pages, which seems unnecessary. Let's consolidate them (and make sure no links are broken by doing so).

*Most recently updated:*
https://dkan.readthedocs.io/en/latest/components/workflow.html?highlight=workflow

https://dkan.readthedocs.io/en/latest/admin/people/dkan_workflow.html?highlight=workflow

**Comment by erogray** [comment]
@stefaniefgray this might be a good project for you when you have the time.

**Comment by stefaniefgray** [comment]
Pull request, ready for QA: https://github.com/GetDKAN/dkan/pull/2707

This is the page we can get rid of: https://dkan.readthedocs.io/en/latest/admin/people/dkan_workflow.html

However, we need to edit the "People" page once this doc is ready so that it links here
https://dkan.readthedocs.io/en/latest/components/workflow.html
