### ISSUE TITLE
Creating Landing pages for topics

### ISSUE THREAD

**Issue by OmarBochkati** [GetDKAN/dkan#2771]
Hi, 

I volunteered at my city's town hall to help create an Open Data catalog. We're using DKAN 7.x-1.15.5 and the issue we're having is we wanted to create a landing page per topic ( more like [data.gov](https://www.data.gov/food/)  ). But I can't find a way to link the pages I create to the topics and update the topics' views.

Thank you for your consideration :)

**Comment by dafeder** [comment]
Hi @OmarBochkati - the redirect from topics pages to the search page is set in:

/admin/config/content/entity_path/list/taxonomy_term%3Adkan_topics/edit

You can disable this redirect and then use ctools/panels to override the term page content and layout. Unfortunately since the entity_paths settings are in the dkan_topics feature, you would need to use features_overrides or some custom method to keep that entity_path setting disabled.

We'd consider a change that would make this easier if you'd like to propose something and submit a PR. Thanks!

I'm going to close this but feel free to re-open if you need more help.
