### ISSUE TITLE
Boolean comparison operators in Datastore API not working

### ISSUE THREAD

**Issue by dafeder** [GetDKAN/dkan#2789]
Great-than or less-than operators are broken in the datastore API. Currently we can only match values, either `x = value` or `x IN (val1,val2,val3)`
```
/**
 * Check which SQL clause should use for conditions.
 */
function dkan_datastore_api_clause_condition($value) {
  return $value == 'NULL' ? 'IS' : 'IN';
}
```

so `&filters[TotalNumberOfFacilities]<3` gives you `WHERE (TotalNumberOfFacilities IN (''))`

**Comment by dharizza** [comment]
Using `&filters[TotalNumberOfFacilities]<3` won't work at all because to get the filters we get the query params, so as it doesn't have the = sign we don't get it right. 

I believe we could use an approach similar to the one used for sorting, so for example we could use an extra key like `&filters[TotalNumberOfFacilities][>]=3` (or instead of > use the word "greater_than" or just "gt", not sure about readibility) and return the condition based on it.

**Comment by dafeder** [comment]
Security updates and bug fixes only in D7. Closing.
