### ISSUE TITLE
SSH timeouts on harvest

### ISSUE THREAD

**Issue by janette** [GetDKAN/dkan#2828]
when nightly harvests run and the source has large imports the process can last longer than 15 minutes and the connection to Acquia is closed automatically.
**dkan_harvest.drush.inc**
```
if ($_migrate_track_timer && !drush_get_context('DRUSH_DEBUG')) {
    drush_print_timers();
  }
```
- Get the debug/print timers info printing to keep the connection open

**Comment by dharizza** [comment]
The caching part works fine but the migrations are the ones who takes a long time without returning results. I tried changing the function used to do the migration in order to use batches instead of running the whole migration in one single run, but the logic used is something similar to one harvest source per batch and in the case we have one source with lots of datasets, the migration still takes a long time. So trying to change the function here https://github.com/GetDKAN/dkan/blob/7.x-1.x/modules/dkan/dkan_harvest/dkan_harvest.drush.inc#L190  to use https://github.com/GetDKAN/dkan/blob/7.x-1.x/modules/dkan/dkan_harvest/dkan_harvest.module#L409 or the _in_batch doesn't work because of that. Also trying to print messages here https://github.com/GetDKAN/dkan/blob/7.x-1.x/modules/dkan/dkan_harvest/dkan_harvest.module#L456 doesn't work either because it prints them at the end of the process so in case we have 1900 datasets in the same source, we still print the progress at the end.

For now I'm thinking on one of these options:
- print messages directly on every dataset migration (as part of the import process for each node), the bad part of these is if we have 1900 datasets, then we would get 1900 messages.
- change batching logic to batch based on datasets and not per harvest source (we could create a new function and see how it goes)
- change the approach to execute the harvest on crun run, that way we avoid the SSH timeouts.

**Comment by dharizza** [comment]
We're going to implement a --feedback option for printing messages frecuently during the migrations. Something similar to https://drushcommands.com/drush-8x/migrate/migrate-import/
