### ISSUE TITLE
Real time datastore API

### ISSUE THREAD

**Issue by datphamict** [GetDKAN/dkan#2844]
Hi everybody,

I would you like to real time datastore API.

Could you please help me to performance?

1.
2.
3.

## Acceptance Criteria
Add the goals and desired results that this issue should accomplish when complete.

- [ ]
- [ ]
- [ ]

## Subtasks
Add a list of things that need to be done to accomplish the Acceptance Criteria.

- [ ] Is there a test for the issue
- [ ] Is there documentation for the issue
- [ ] Are follow up tickets needed

**Comment by kimwdavidson** [comment]
@datphamict, can you tell us a bit more about what you're trying to accomplish?

**Comment by dafeder** [comment]
@datphamict, we're going to close this because you haven't provided more details, but I assume you're talking about an API that would let you stream realtime data into a datastore table. This kind of thing is on the longterm roadmap but likely requires rearchitecting the datastore as a separate service. Feel free to open this ticket back up if you want to continue discussing it or to follow one of the other open issues about decoupling the datastore.
