### ISSUE TITLE
Subsequent Harvests should continue to run even if one has errors

### ISSUE THREAD

**Issue by erogray** [GetDKAN/dkan#2891]
## User Story
As a site manager for a site with multiple harvests, I want as many harvests as possible to complete successfully, even if one of the harvests has errors, so that my site data can be as up-to-date as possible.

## Problem
Currently if a DKAN site has multiple harvests, and one stops with errors, all harvests that run afterward do not run. For sites with many harvests, this can mean that a single dataset with (for instance) an unusual date format, can cause hundreds or even thousands of other datasets in subsequent harvests to not update.

**Comment by erogray** [comment]
@dharizza what would be the level of effort here (approximately)? Curious about whether this should be worked on in DKAN 1 vs. DKAN 2.

**Comment by dharizza** [comment]
@erogray I believe we may need a better definition of "stops with errors" in order to know the level of effort here. For example, we were having issues with date formats like "YYYY-YYYY" and then an exception not handled was thrown, that was preventing every subsequent harvest from running because it interrupted the usual workflow, that kind of errors needs fixing, in this case we fixed it in https://github.com/GetDKAN/dkan/pull/2892 and now even if the harvest "finishes with errors" (for example, format errors in some fields or files not found) the subsequent harvest are run and we get the notice about the harvest that finished with errors.

**Comment by erogray** [comment]
Seems fixed-ish.
