### ISSUE TITLE
Group descriptions truncate awkwardly

### ISSUE THREAD

**Issue by erogray** [GetDKAN/dkan#2900]
Group descriptions are truncated mid-word on the Groups pages. Eg: https://data.ca.gov/groups or https://data.louisvilleky.gov/groups?page=0%2C3 or https://gishubdata.nd.gov/groups

It'd be better to truncate text at a space instead, and add a "..." at the end.

![Screen Shot 2019-06-11 at 1.15.07 PM.png](https://images.zenhubusercontent.com/599604c58f62dc7798c32ff7/00b64da4-c897-4e55-ba78-cc90b87838da)
![Screen Shot 2019-06-11 at 1.15.54 PM.png](https://images.zenhubusercontent.com/599604c58f62dc7798c32ff7/79b2c107-4503-4498-91dd-a47ceb04d06b)
![Screen Shot 2019-06-11 at 1.17.52 PM.png](https://images.zenhubusercontent.com/599604c58f62dc7798c32ff7/fee51ee0-6aa4-44c8-94a0-08d5535ba6bc)

**Comment by stefaniefgray** [comment]
**Schneurle update:**

This is what he would like us to do:

Add a second field to the group description, so that one could type both a full description (for the group sidebar) and a shorter "teaser text" version (for the Groups page). That second one looks like it should be <140 characters. 

@dharizza Can we get an estimate on how long this would take? Thanks!

**Comment by dharizza** [comment]
That field is already a long text and summary field, so I think we should just activate that option for the users to be able to edit the summary, so if summary is added that will be shown, otherwise, trimmed body will be shown. I'd say whole work would take 2h top.

**Comment by stefaniefgray** [comment]
Emailed Schneurle in opendata-632; waiting on response
