### ISSUE TITLE
Does Dkan complete Spanish? where can i download it

### ISSUE THREAD

**Issue by vmendieta** [GetDKAN/dkan#2933]
Does Dkan complete Spanish? where can i download it

**Comment by managume** [comment]
Nowadays there's no a complete Spanish translation for DKAN. Just a Spanish (Colombian) translation but not too much complete. Here you are [the link](https://github.com/angrycactus/dkan_l10n_es_co)

**Comment by rhabbachi** [comment]
Hey @managume, been a while since I worked on that module. Wondering how was you experience working with it? Are you planning on using it for a production install?

**Comment by managume** [comment]
Hi @rhabbachi! Yes, we want to use it in prod. It's a big first helpful step so thanks :) Now we're having some problems installing whole Spanish translation. Maybe first reason is because DKAN doesn't support multilanguage as we thought. I'm installing your module using l10n_update but some Drupal 7 core translation breaks some DKAN functionalities. I'm on it now trying to solve it.

**Comment by vmendieta** [comment]
mport the .po files from the link
How can I make my own .po to translate what is missing? for example:
![imagen](https://user-images.githubusercontent.com/8810083/62560317-c85adf00-b84a-11e9-8ada-81e85cb208a7.png)

**Comment by janette** [comment]
@managume if you can report back your findings/updates we'd love to incorporate them into a future release, and improve the documentation.

**Comment by vmendieta** [comment]
@managume @rhabbachi @janette  With that information, more my translations I have been able to translate up to a little more than 70%, but there are functionalities that present problems as in [#2936](https://github.com/GetDKAN/dkan/issues/2936) it can be read that they already reported it before, in English works, so I will be looking for a solution and I will publish it if I find it, while if I need those functionality I will put it in English and then I will return to Spanish, it is a temporary solution

**Comment by ElDabbo** [comment]
I installed this module, but there is no changes at the language, any advice of use or how can i translate dkan for drupal 7? please

**Comment by managume** [comment]
@ElDabbo you have two options:

- Run [drush command](https://github.com/angrycactus/dkan_l10n_es_co/blob/7.x-1.x/dkan_l10n_es_co.drush.inc) that appears with you install the translation module.
- Or install the [l10n_update module](https://www.drupal.org/project/l10n_update) and run it, but be careful because the core Drupal translation breaks some DKAN functionalities so proceed with caution.

**Comment by susisiman** [comment]
https://github.com/angrycactus/dkan_l10n_es_co @vmendieta see if this helps!
