### ISSUE TITLE
PyDKAN

### ISSUE THREAD

**Issue by phwegner** [GetDKAN/dkan#2993]
Im currently using PyDKAN to create Datsets. I want to do this with a json that contains all Meta Data I need to know. The problem ist the structure of such a json file. I tried :

```
{
    "body": {
        "und": {
            "0": {
                "value": "The DisGeNET database integrates information of human gene-disease associations (GDAs) and variant-disease associations (VDAs) from various repositories including Mendelian, complex and environmental diseases. The integration is performed by means of gene and disease vocabulary mapping and by using the DisGeNET association type ontology. For more details, see the original publications: Piñero et al., 2016 , Piñero et al., 2015 , Bauer-Mehren et al., 2011 and Bauer-Mehren et al., 2010 . "
            }
        }
    },
    "title": "DisGeNET",
    "field_author": {
        "und": {
            "0": {
                "value": "DisGeNET"
            }
        }
    },
    "og_group_ref": "DisGeNET",
    "field_tags": {
        "und": {
            "0": {
                "value": "genes, human diseases,animal models, community-driven ontologies, genotype/phenotype relationships "
            }
        }
    },

    "field_license": [{
        "name": "Attribution-NonCommercial-ShareAlike 4.0 International License",
        "value": "https://creativecommons.org/licenses/by-nc-sa/4.0/"
    }],
    "field_additional_info": {
        "und": {
            "0": {
                "value": " UNIPROT, CTD, ORPHANET, CLINGEN, GENOMICS ENGLAND, CGI, PSYGENET"
            },
            "1": {
                "value": "Animal Models Data: CTD Rat and CTD Mouse: CTD, MGD, RGD"
            }
        }
    }
}
```

Is there any documentation where I can find what field needs what structure because right now Im getting
 ```
500
["Invalid option for field field_tags"]
```
Im using the following Script: 
```
with open(args.dataset, "r") as f:
        data = json.load(f)
        
        data["type"] = "dataset"

        # Create Dataset-NODE
        api = DatasetAPI(URL, USER, PASSWORD, True)
        dataset = api.node("create", data=data)
        print(dataset.status_code)
        print(dataset.text)
        node_id = json.loads(dataset.text)["nid"]
        if dataset.status_code == HTTPStatus.OK:
            print(
                "\n \n -------CREATED DATASET WITH NODE ID "
                + node_id
                + "--------- \n \n"
            )
```

**Comment by kkwaiser** [comment]
One option is to install the Devel module, enable the execute php block and then load and print an example dataset. 

For example, entering this text into the execute PHP block for a dataset (node 38)
```
$node = node_load(38);
dpm($node);
```
![image](https://user-images.githubusercontent.com/20301346/74965545-6d05ce00-53e3-11ea-8231-acfd0f86c49c.png)

and then printing the node object using the dpm() command shows the following. 

![image](https://user-images.githubusercontent.com/20301346/74965357-18fae980-53e3-11ea-990f-de0aca851396.png)

Of course, allowing open execution of PHP on your website has security implications and wouldn't be recommended for production sites. Field_tags is also expecting an integer identifier (e.g., term ID or TID) rather than a text string. You'll need to obtain these from the tags taxonomy via a lookup of some sort.

**Comment by tomsrocket** [comment]
Another way that helped me was: 
1. Go to the DKAN Administration interface, to the "Create Dataset"-Page
2. Fill out all the fields 
3. Open the developer console of your internet browser (e.g. Firefox: right click inside page, "inspect element") 
4. In developer console navigate to the "Network" tab, make sure the box "Persist logs" is checked, so the history will not be cleared after page load
5. Click "submit" button in DKAN
6. In network tab, find the POST request that submitted the data. Check the data structure that was posted. 

BTW, the solutions for the above error "Invalid option for field field_tags" is: 
In "field_tags" you need to use "value_field" instead of "value".
