### ISSUE TITLE
Make front end work with React App

### ISSUE THREAD

**Issue by kimwdavidson** [GetDKAN/dkan#3097]
## User Story
As a developer with a lot of datasets in my catalog, I want to use a create-react-app frontend, so I can update a page without having to rebuild and make changes quickly.

## Acceptance Criteria
- [ ] Both dynamicly- and staticly-generated routing is supported
- [ ] Frontend module detects which method by looking at how many files there are
- [ ] If staticly-generated (many files), a Drupal route is created for each static page
- [ ] If dynamically-generated (only one file exists), all Drupal routes (except admin/*) are redirected to that file

## Details/Tasks
- [ ] make DKTL choose between gatsby and react app (captured in GetDKAN/dkan-tools#227)

Note: This is essentially a quick-fix to switch from Gatsby to create-react-app, we expect to deprecate in the future

**Comment by dgading** [comment]
`Frontend module detects which method by looking at how many files there are` instead of this, I updated the module to read the frontend package.json and choose by looking for Gatsby. I can easily update this in the future with the new config file added that includes a static boolean we can surface in the event something other than Gatsby is used.

**Comment by dgading** [comment]
`If dynamically-generated (only one file exists), all Drupal routes (except admin/*) are redirected to that file` I've also made a change here. There could be use cases where not all the routes should be served by React so I made a config file that can take a list of routes to replace the folder browsing we are doing on the Gatsby side. We may still need a solution for 404s since Drupal is still serving those and that should also be the React app.
