### ISSUE TITLE
Convert all sample content CSVs to UTF-8

### ISSUE THREAD

**Issue by kimwdavidson** [GetDKAN/dkan#3115]

**Comment by rhabbachi** [comment]
Currently working on this ticket. Following is the latest update on the progress I made:

The need for this ticket came from the garbled output shown in the "Afghanistan Election Districts" dataset from the sample content.

![image.png](https://images.zenhubusercontent.com/558811a24f7a08fbb7f354f6/64f25ef8-793a-49c5-85ad-13d45a3a3d19)

I believe the initial though was the corrupted display was due to the CSV file not being UTF8 encoded. When making sure that the text file is UTF8, the issue still pops up again.

Digging more turns out that the Datastore API had the same problem and returned garbled text, the frontend was just displaying what it got.

 Looking at the database table used by the datastore to store the tabular content, the corrupted content is there as well. The API is most likely working as it should.

![image.png](https://images.zenhubusercontent.com/558811a24f7a08fbb7f354f6/f1e23e89-e8dd-4289-baa5-8d93143291cb)

After some debugging, I was able to import the content of the district file by disabling the utf8 encoding in the getdkan/datastore library (exact line https://github.com/GetDKAN/datastore/blob/master/src/Importer.php#L114). The double encoding caused the non-Latin text to get corrupted.

**Comment by janette** [comment]
nice find @rhabbachi , maybe we should assume utf-8 and add an argument to the import call to add the encoding if needed.

**Comment by rhabbachi** [comment]
From what I've seen in the code, the goal is to transcode everything to UTF-8 inside the database. This makes sense as the APIs will have a stable encoding that the consumer applications can reliably use.

Supporting the source encoding as an optional argument sounds like it will cover all the cases, but can be tiresome as well. We will need to build a form to take the distribution encoding and stored somewhere. We will potentially need to add support for a custom field in the schema to save that kind of information.

To buy us time until we design and plan the proper solution, I found this small PHP library [https://github.com/neitanod/forceutf8] that assumes the input to be encoded to either Windows-1252 or ISO 8859-1, which should be sufficient to work with the most used encodings in the industry. Replacing the faulty double encoding with it seems to be working well with the District sample content CSV.

![image.png](https://images.zenhubusercontent.com/558811a24f7a08fbb7f354f6/af8f0a2c-04de-4854-b521-9c368c74722a)

I ran a couple of tests, and it seems it does not have an impact on the import time.

PR available here [https://github.com/GetDKAN/datastore/pull/27] @janette let me know what you think!
