### ISSUE TITLE
Discovery: Unpublished datasets and resources

### ISSUE THREAD

**Issue by susisiman** [GetDKAN/dkan#3219]
Determine how to manage unpublished datasets that cannot be deleted from sites moving to DKAN2. Figure out how long it will take to migrate them through each strategy. Functionality is in DKAN2 but the content needs to be migrated. Current approach for migration is on harvest and harvest only migrates publish.   

User Stories: 
- I am creating a new dataset but it is not ready for published because I need to add metadata, write a better description, etc. 

- Someone has left the organization and we'd like to retain what they published but do not want it on the live site. 

- There is a dataset or other piece of content that has been outdated but is still relevant to hold on to.

- i want to archive my datasets

**Comment by janette** [comment]
RE: scrum convo

Export unpublished datasets as packages and import into dkan2 or write new REST service to migrate unpublished or private datasets

**Comment by rhabbachi** [comment]
The goal is to have a self contained archive with the unpublished datasets and associated resources.

1. Multiple paths are available:
**Using the REST API**
Leverage DKAN REST APIs via a script.
- Unpublished Datasets Is not exposed unless we patch the contrib module.
- Would not be deploy-able since it will introduce practically a vulnerability.

2. **Run SQL queries**
Write custom SQL queries 
+ Custom tailored solution.
- Would take too much efforts.

3. **dkan_fixture/open_data_schema_map**
Use `dkan_fixture` or reuse some code bits from it to export unpublished datasets into a self contained archive. Either creating a new open_data_schema_map schema or leveraging the ckan schema currently used by `dkan_fixture`.
+ Leverage Existing code/infrastructure.
+ Controlled patching should not introduce a vulnerability.
- Need to patch for unpublished datasets support.

Option 3 is the most sensible option.
