### ISSUE TITLE
Fix email validation on json form widget

### ISSUE THREAD

**Issue by kimwdavidson** [GetDKAN/dkan#3312]
## Background ##
The schema requires the format "mailto:(email address)"

But most users will expect to just put their email address in without "mailto:" in front of it. We want to add "mailto:" for them. 

We also need to ensure validate that entered emails include .domain.

## Tasks ##
- support option in schema UI
- prepend to the value

## Acceptance Criteria ##
- When I create dataset
- And go to the contact section
- And enter an email address in the format "name@service.whatever"
- And the rest of the form is filled out properly
- I don't see an error
- And I see my email display properly on the dataset

**Comment by dharizza** [comment]
After more discovery, we found out the issue is not related to the lack of "mailto" in user input, instead any kind of email that doesn't follow the pattern `address@domain.something` is shown as a failure, also the error isn't flagged in the specific subfield so we changed the approach to improve validation, flag the right field and still accomplish the acceptance criteria defined here, the PR that fixes this issue is https://github.com/GetDKAN/dkan/pull/3336
