### ISSUE TITLE
PHPUnit 7.5.20 is no longer supported

### ISSUE THREAD

**Issue by thierrydallacroce** [GetDKAN/dkan#3380]
Just spun up a new site from scratch locally, to see which version of PHPUnit DKAN is using:

```
❯ ./vendor/bin/phpunit --version
PHPUnit 7.5.20 by Sebastian Bergmann and contributors.
```

According to https://phpunit.de/supported-versions.html, this version of PHPUnit has not been supported for over a year.

Assuming there's nothing blocking this, like a license incompatibility, ideally DKAN (and DKAN Tools?) should be running a newer, supported version of PHPUnit. Preferably version 9, the newest, as its requirement of PHP 7.3 seems to match DKAN's.

**Comment by fmizzell** [comment]
@thierrydallacroce Drupal 9.0.x uses PHPUnit 8.4. We can up DKAN to that.

**Comment by paul-m** [comment]
This project's PHPUnit constraint was moved to `^8.5.14 || ^9` in https://github.com/GetDKAN/dkan/pull/3604

Since it's probably not the root package, the `require-dev` will get obliterated by `drupal/core-dev`, but that's fine because `drupal/core-dev` for the 9.3 branch has the [same PHPUnit constraint](https://git.drupalcode.org/project/drupal/-/blob/9.3.x/composer.json#L25).
