### ISSUE TITLE
Date widgets within json metadata field are saving dates in the incorrect format

### ISSUE THREAD

**Issue by brianseek** [GetDKAN/dkan#3540]
## Describe the bug
If you create a node from the node edit form, the dates get saved in this format: "2021-06-01 10:35:25 America/New_York"
The format should be: "2021-06-01T10:35:25+00:00"

## Steps To Reproduce
Create a new data node and fill in the dates with the widget. Then view the data saved in the database.

## Expected behavior
The data should be saved in the format: "2021-06-01T10:35:25+00:00"

##Estimate: 1

**Comment by dharizza** [comment]
This is fixed in https://github.com/GetDKAN/dkan/pull/3545
I found a bug with the DateRange element where if the user doesn't fill those values (in this case the temporal field), the field gets the value of "/" and the next time you load the form you see the current date as start and end date, so that's fixed in the same PR.
