### ISSUE TITLE
Distribution files that failed to import will prevent future imports of the same file

### ISSUE THREAD

**Issue by janette** [GetDKAN/dkan#3603]
## Describe the bug
If a dataset is created with a csv distribution, and there is a failure on the resource importer, attempting to use that file again will point the new use case to the failed datastore import.

## Steps To Reproduce
- make your sites/default/files directory unwritable
- create a dataset with a csv distribution
- run cron
- fix write access to sites/default/files
- create a new dataset and use the same csv file for the distribution

**Comment by grugnog** [comment]
Was finally able to reproduce this as part of working on #3605 - using "https://download.medicaid.gov/data/newNADACPrice.csv" as a remote URL on 2.x creates a distribution with an MIME type that will not trigger the importer.

If you then fix that issue and create a new dataset reusing the same "https://download.medicaid.gov/data/newNADACPrice.csv" URL you will notice that no new distribution is created. This is because it is reusing the reference from the prior dataset.

If you go and look at the original distribution you can see that it also hasn't been updated with the new MIME type.

Because no new distribution or distribution version is being stored the ResourceMapper:EVENT_REGISTRATION event is not triggered, which is what the DatastoreSubscriber listens to for queuing import tasks.

The code in question is in https://github.com/GetDKAN/dkan/blob/d1b8249da2719ebbe68b4a7d93172ac47394ffd5/modules/metastore/src/Reference/Referencer.php#L196

The line `if ($info[0]->perspective == Resource::DEFAULT_SOURCE_PERSPECTIVE && resource_mapper_new_revision() == 1) {` returns false, causing it to return with the existing datastore identifier.

**Comment by grugnog** [comment]
Added a PR that fixes this - I am not very sure if this is the right place/approach though - this approach only accounts for changing MIME types, I am not sure if there are other things we need to look at also. In general it seems quite mysterious if/how a new version would ever get saved in the first place?

**Comment by dafeder** [comment]
@grugnog works great but needs tests, see PR. I can write the tests if you're busy with other things now.

WRT your question, this PR would ensure that a new resource version (which means a new datastore import job is queued) is created under the following conditions:

1. The downloadURL changes
2. One of the "triggering" dataset properties changes (see #3552)

If the downloadUrl changes, that creates a completely new resource, which will have essentially the same effect from the user standpoint. So these are the three ways to tigger a datastore re-import. Obviously, this all needs to be documented more clearly!
