### ISSUE TITLE
Changing the resource URL on a dataset deletes the datastore for other datasets that used the same resource URL

### ISSUE THREAD

**Issue by grugnog** [GetDKAN/dkan#3647]
## Describe the bug

Changing the resource URL on a dataset deletes the datastore for other datasets that used the same resource URL.

Just like we do for keyword references, check if other distributions using the resource reference before orphaning/deleting.

## Steps To Reproduce

- Create dataset A with resource URL https://people.sc.fsu.edu/~jburkardt/data/csv/ford_escort.csv
- Create dataset B with resource URL https://people.sc.fsu.edu/~jburkardt/data/csv/ford_escort.csv
- Run `dktl drush queue:run datastore_import`
- Observe that the datastore preview is visible on both dataset pages
- Edit dataset B and change the resource URL to https://people.sc.fsu.edu/~jburkardt/data/csv/tally_cab.csv
- Run `dktl drush queue:run resource_purger`
- Observe that dataset A (even though that was not edited) has had it's datastore removed

## Expected behavior

If a user edits one dataset other datasets are not changed.
If DKAN deduplicates resources (and datastores for these resources) behind the scenes this needs to be transparent to the user without unexpected side effects.

## Notes

When testing this we should test with and without identical distribution metadata (see #3648) - currently this reproduces in both cases.

Looking through the ResourcePurger service it seems like resources being shared by multiple distributions is not currently being taken into account.

**Comment by clayliddell** [comment]
The behavior observed in this issue is a direct consequence of resources being unknowingly shared between multiple distributions. #3648 doesn't appear to be contributing to this issue directly, however it could potentially cause problems depending on what solution we devise, since shared distributions may make it difficult to detect shared resources.

The only way to determine what resource belongs to a given distribution is through the `field_json_metadata` distribution node field. So, if you wanted to determine whether a resource was in use by more than one distribution, you would have to:
1. Fetch and iterate over every distribution node.
2. Fetch and parse the JSON metadata for each node.
3. Determine whether the resource ID stored within the JSON metadata matches the ID of the resource being deleted.
4. Keep a count of the matching resource IDs.
5. Only proceed with deleting the resource if only one distribution has a resource with the ID being terminated.

As an aside, the above procedure would be very inefficient since terminating an orphaned resource would require every distribution to be fetched, parsed, and inspected; this might could be improved by using a SQL query, for example: 
```php
\Drupal::entityQuery('node')
  ->condition('type', 'data')
  ->condition('field_json_metadata', '"identifier":"' . $resource_id . '"', 'CONTAINS')
  ->count()
  ->execute();
```

Alternatively, we could disallow shared resources across distributions and force each distribution to have a unique resource. This could be enforced by just generating a unique resource ID, independent of the resource itself.

I personally think the best way forward would be the SQL/entity-query approach from option 1; however, this approach only highlights how fragile it is to depend on the JSON metadata field for a distribution as the sole source of truth for relationships between distributions and resources. It seems we would benefit from reconsidering how datasets are currently architected in DKAN, and, at the very least, migrating the properties currently stored in the JSON metadata field to fields of their own. This would prevent us from having to parse the JSON metadata for a distribution before interacting with any of a dataset's metadata.

**Comment by clayliddell** [comment]
My suspicion that #3648 could come in the way of detecting shared resources is correct. We would benefit from first resolving #3648, since that will allow us to query for a dataset by it's distribution's resource ID.

Update: Following a discussion with @dafeder, it seems better to operate under the assumption that a distribution may be shared by multiple datasets for the implementation of this feature.

**Comment by clayliddell** [comment]
This is currently blocked by PR #3661.
