### ISSUE TITLE
DKAN calculating checksum on files during datastore API request

### ISSUE THREAD

**Issue by grugnog** [GetDKAN/dkan#3669]
## Describe the bug
Datastore queries (/api/1/datastore/query/...) became exceedingly slow somewhere [in between these 2 commits](https://github.com/GetDKAN/dkan/compare/25970d11231f91c072704532f2ad27fed9f2da33...26ba53d).

We captured a stack track and it appears to be that these requests are calculating a checksum for files during the request, which seems almost certainly the culprit, and is very likely unintentionally introduced behavior.
![image](https://user-images.githubusercontent.com/905689/134409088-a88f96ae-942c-4687-841c-134d2fe87de2.png)

## Steps To Reproduce
- Create a large dataset
- Time a datastore query with the first/last commits linked above

## Expected behavior
- The datastore query response time should be as fast as it was previously

**Comment by clayliddell** [comment]
Just a couple thoughts from reading through the problematic code:

1. We should probably be storing the dataset file hash independent of the perspective (since one file usually has 3 perspectives).
2. After reading through the initial ticket, it seems unnecessary for us to generate the hash for the file on dataset perspective creation, we could instead just generate it whenever the file is fetched/uploaded (or create a queue specifically for this purpose and just create queue jobs whenever the file is fetched/uploaded).

Also, here's the PR which introduced the bug for reference: https://github.com/GetDKAN/dkan/pull/3596
