### ISSUE TITLE
Datastore API issue

### ISSUE THREAD

**Issue by DaniyalRaza786** [GetDKAN/dkan#4052]
I want to fetch all the data from the resource files at once. So we tried **/API/1/datastore/query** with the 'GET' method as mentioned in the documentation, but it gave an empty result on the demo.getdkan.com website. How can I resolve this issue? And the second thing is datastore API show only CSV file's data, but we need to show CSV and excel file how can I fetch for both file data at a time if have any possibilities please suggest me.

PFA
![Screenshot from 2023-11-07 14-48-09](https://github.com/GetDKAN/dkan/assets/49777122/9c6bd690-fd1d-4321-bb62-0ed5b8eeaa19)
![Screenshot from 2023-11-07 14-45-31](https://github.com/GetDKAN/dkan/assets/49777122/6bd199cd-3864-4b04-8c68-4fe9dc280cf9)

**Comment by dafeder** [comment]
Hi @DaniyalRaza786. You need to provide an identifier to the datastore API so that it can know what table to show. Usually this is done by adding it directly to the endpoint, so api/1/datastore/query/[distribution-id] or api/1/datastore/query/[dataset-id]/[index] - the index being which number in the distribution array your table occupies (often "0").

So for instance for 

https://demo.getdkan.org/dataset/5dc1cfcf-8028-476c-a020-f58ec6dd621c

We can query 

https://demo.getdkan.org/api/1/datastore/query/5dc1cfcf-8028-476c-a020-f58ec6dd621c/0

The datastore can only run queries on resources that have been imported to the database. At the moment, DKAN can only import CSV files.

**Comment by dafeder** [comment]
Closing this, assuming its resolved
