### ISSUE TITLE
/health or /status API Endpoint

### ISSUE THREAD

**Issue by TheBoatyMcBoatFace** [GetDKAN/dkan#4195]
## User Story
When checking the status of the dkan demo, we use the following URL
`https://demo.getdkan.org/api/1/search?fulltext=&page=1&page-size=10&sort=modified&sort-order=desc&facets=0`

This type of call seems a little overkill for checking to make sure the API is operational and healthy. If the wrong query is used, it could use an unnecessarily high amount of server resources, possibly resulting in micro downtimes.

It would he helpful to have a `/status` or `/health` type endpoint which responds with `OK`, `NOT OK`, or some variation of version, uptime, etc.. info.

I couldn't find this in the API documentation, but if it exists, please close this issue.

## Acceptance Criteria
- [ ] A lighter weight or better-defined status or health check

**Comment by paul-m** [comment]
For the demo site, we could consider using the health check module: https://www.drupal.org/project/health_check

**Comment by dafeder** [comment]
Yes, I believe this is outside the scope of DKAN's own API. If what you're looking for is overall performance I think we want something external to DKAN or even probably Drupal that would be checking for latency or transfer speeds from outside our infrastructure? That particular one really should not be very expensive, but there are cheaper ones that could be used, such as requesting a specific dataset by ID rather than searching the whole catalog.
